### ISSUE TITLE
Document the advantages over alias

### ISSUE THREAD

**Issue by antony** [csabapalfi/macos-airport#1]
This project doesn't list the advantages this module has over the `alias` command:

`alias airport /System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport`

**Comment by csabapalfi** [comment]
The main advantage I can think of is not having to remember (or google) the location of airport binary, like ever. All I got to remember is that there's module called `macos-airport`.

tbh I could've just added this to my dotfiles repo as an alias but this way I can have this any machine that has node. Which is another stupid trade-off as `alias` is on all Macs but node isn't. 

Also the module name `airport` was taken so it's slightly more cognitive load to remember `macos-airport`.

**Comment by csabapalfi** [comment]
What I mean is not having to remember/google the location when setting the alias the first time. 

It's kind of like abusing a node module on npm as your alias in the cloud ☁️ 🤣 

Of course on most of my regularly used machines I use my dotfiles repo so this whole thing could still be pointless.
